# Generated by Django 4.1.5 on 2023-02-06 05:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('earlydate', models.DateField()),
                ('earlytime', models.TimeField()),
                ('latedate', models.DateField()),
                ('latetime', models.TimeField()),
                ('seats_needed', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats_needed', models.PositiveSmallIntegerField()),
                ('driver_name', models.CharField(blank=True, default='', max_length=50)),
                ('driver_license', models.CharField(blank=True, default='', max_length=50)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('share_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=10)),
                ('required_type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('TRUCK', 'TRUCK')], default='--', max_length=20)),
                ('special_requirement', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ride_status', models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Open', max_length=10)),
                ('current_passengers', models.SmallIntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
