# Generated by Django 4.1.5 on 2023-02-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='ride_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.riderequest'),
        ),
    ]
