# Generated by Django 4.1.5 on 2023-02-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_searchrequest_ride_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='required_type',
            field=models.CharField(blank=True, choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('TRUCK', 'TRUCK')], max_length=20),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='early_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='late_datetime',
            field=models.DateTimeField(),
        ),
    ]
