# Generated by Django 4.1.5 on 2023-02-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_riderequest_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='sharer_information',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
