# Generated by Django 4.1.5 on 2023-01-31 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_driver', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('TRUCK', 'TRUCK')], max_length=20)),
                ('license_plate', models.CharField(blank=True, default='', max_length=20)),
                ('special_info', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
