# Generated by Django 4.1.5 on 2023-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('TRUCK', 'TRUCK'), ('--', '--')], max_length=20),
        ),
    ]
