# Generated by Django 4.1.5 on 2023-02-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('TRUCK', 'TRUCK')], max_length=20),
        ),
    ]
